// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260704221434_UpdateProductImages")]
    partial class UpdateProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ProductDescription = "Apple iPhone 16 Pro 256 GB",
                            ProductImageUrl = "https://picsum.photos/id/101/500/500",
                            ProductName = "iPhone 16 Pro",
                            ProductPrice = 89999m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ProductDescription = "Samsung Galaxy S25 256 GB",
                            ProductImageUrl = "https://picsum.photos/id/102/500/500",
                            ProductName = "Samsung Galaxy S25",
                            ProductPrice = 74999m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            ProductDescription = "Apple MacBook Air M4 13 inç",
                            ProductImageUrl = "https://picsum.photos/id/103/500/500",
                            ProductName = "MacBook Air M4",
                            ProductPrice = 62999m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            ProductDescription = "Kablosuz Profesyonel Mouse",
                            ProductImageUrl = "https://picsum.photos/id/104/500/500",
                            ProductName = "Logitech MX Master 3S",
                            ProductPrice = 4499m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            ProductDescription = "27 İnç 2K IPS Monitör",
                            ProductImageUrl = "https://picsum.photos/id/105/500/500",
                            ProductName = "Dell UltraSharp 27",
                            ProductPrice = 14999m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            ProductDescription = "Kablosuz Gürültü Engelleyici Kulaklık",
                            ProductImageUrl = "https://picsum.photos/id/106/500/500",
                            ProductName = "Sony WH-1000XM5",
                            ProductPrice = 12999m,
                            Stock = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
